package com.company.carrental.core.model;

// default package
// Generated 17 Nov, 2012 7:41:40 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DriverMaster generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "driver_master", catalog = "Car_Rental")
public class DriverMaster implements Serializable {

	private int driverId;

	private String driverFullName;

	private char gender;

	private Date dob;

	private Float totalExperience;

	private String primaryContactNumber;

	private Integer currentAreaId;

	private String licenceNo;

	private String licenceType;

	private Date licenceExpiryDate;

	private Character jobPrefIndividual;

	private Character jobPrefCorporate;

	private Character jobPrefTemporary;

	private Character jobPrefPermanent;

	private Character jobPrefAdhoc;

	private Character carTypeAutomatic;

	private Character carTypeManual;

	private Integer ratingId;

	private String referenceName;

	private String referenceNumber;

	private String medicalHistory;

	private String accidentHistory;

	private Set<DriverContact> driverContacts;
	
	private Set<DriverAddress> driverAddress;
	
	private Set<DriverCarTypes> driverCarTypes;
	
	private Set<DriverDocumentsList> driverDocumentsLists;

	public DriverMaster() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Driver_Id", unique = true, nullable = false)
	public int getDriverId() {
		return this.driverId;
	}

	public void setDriverId(int driverId) {
		this.driverId = driverId;
	}

	@Column(name = "Driver_FullName", nullable = false)
	public String getDriverFullName() {
		return this.driverFullName;
	}

	public void setDriverFullName(String driverFullName) {
		this.driverFullName = driverFullName;
	}

	@Column(name = "Gender", nullable = false, length = 1)
	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 0)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Total_Experience", precision = 12, scale = 0)
	public Float getTotalExperience() {
		return this.totalExperience;
	}

	public void setTotalExperience(Float totalExperience) {
		this.totalExperience = totalExperience;
	}

	@Column(name = "Primary_Contact_Number", nullable = false, length = 16777215)
	public String getPrimaryContactNumber() {
		return this.primaryContactNumber;
	}

	public void setPrimaryContactNumber(String primaryContactNumber) {
		this.primaryContactNumber = primaryContactNumber;
	}

	@Column(name = "Current_Area_Id")
	public Integer getCurrentAreaId() {
		return this.currentAreaId;
	}

	public void setCurrentAreaId(Integer currentAreaId) {
		this.currentAreaId = currentAreaId;
	}

	@Column(name = "Licence_No")
	public String getLicenceNo() {
		return this.licenceNo;
	}

	public void setLicenceNo(String licenceNo) {
		this.licenceNo = licenceNo;
	}

	@Column(name = "Licence_Type")
	public String getLicenceType() {
		return this.licenceType;
	}

	public void setLicenceType(String licenceType) {
		this.licenceType = licenceType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Licence_Expiry_Date", length = 0)
	public Date getLicenceExpiryDate() {
		return this.licenceExpiryDate;
	}

	public void setLicenceExpiryDate(Date licenceExpiryDate) {
		this.licenceExpiryDate = licenceExpiryDate;
	}

	@Column(name = "Job_Pref_Individual", length = 1)
	public Character getJobPrefIndividual() {
		return this.jobPrefIndividual;
	}

	public void setJobPrefIndividual(Character jobPrefIndividual) {
		this.jobPrefIndividual = jobPrefIndividual;
	}

	@Column(name = "Job_Pref_Corporate", length = 1)
	public Character getJobPrefCorporate() {
		return this.jobPrefCorporate;
	}

	public void setJobPrefCorporate(Character jobPrefCorporate) {
		this.jobPrefCorporate = jobPrefCorporate;
	}

	@Column(name = "Job_Pref_Temporary", length = 1)
	public Character getJobPrefTemporary() {
		return this.jobPrefTemporary;
	}

	public void setJobPrefTemporary(Character jobPrefTemporary) {
		this.jobPrefTemporary = jobPrefTemporary;
	}

	@Column(name = "Job_Pref_Permanent", length = 1)
	public Character getJobPrefPermanent() {
		return this.jobPrefPermanent;
	}

	public void setJobPrefPermanent(Character jobPrefPermanent) {
		this.jobPrefPermanent = jobPrefPermanent;
	}

	@Column(name = "Job_Pref_Adhoc", length = 1)
	public Character getJobPrefAdhoc() {
		return this.jobPrefAdhoc;
	}

	public void setJobPrefAdhoc(Character jobPrefAdhoc) {
		this.jobPrefAdhoc = jobPrefAdhoc;
	}

	@Column(name = "Car_Type_Automatic", length = 1)
	public Character getCarTypeAutomatic() {
		return this.carTypeAutomatic;
	}

	public void setCarTypeAutomatic(Character carTypeAutomatic) {
		this.carTypeAutomatic = carTypeAutomatic;
	}

	@Column(name = "Car_Type_Manual", length = 1)
	public Character getCarTypeManual() {
		return this.carTypeManual;
	}

	public void setCarTypeManual(Character carTypeManual) {
		this.carTypeManual = carTypeManual;
	}

	@Column(name = "Rating_Id")
	public Integer getRatingId() {
		return this.ratingId;
	}

	public void setRatingId(Integer ratingId) {
		this.ratingId = ratingId;
	}

	@Column(name = "Reference_Name")
	public String getReferenceName() {
		return this.referenceName;
	}

	public void setReferenceName(String referenceName) {
		this.referenceName = referenceName;
	}

	@Column(name = "Reference_Number", length = 16777215)
	public String getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	@Column(name = "Medical_History")
	public String getMedicalHistory() {
		return this.medicalHistory;
	}

	public void setMedicalHistory(String medicalHistory) {
		this.medicalHistory = medicalHistory;
	}

	@Column(name = "Accident_History")
	public String getAccidentHistory() {
		return this.accidentHistory;
	}

	public void setAccidentHistory(String accidentHistory) {
		this.accidentHistory = accidentHistory;
	}

	@OneToMany(mappedBy = "driverMaster")
	public Set<DriverContact> getDriverContacts() {
		return driverContacts;
	}

	public void setDriverContacts(Set<DriverContact> driverContacts) {
		this.driverContacts = driverContacts;
	}

	@OneToMany(mappedBy = "driverMaster")
	public Set<DriverAddress> getDriverAddress() {
		return driverAddress;
	}
	
	public void setDriverAddress(Set<DriverAddress> driverAddress) {
		this.driverAddress = driverAddress;
	}

	
	public void setDriverCarTypes(Set<DriverCarTypes> driverCarTypes) {
		this.driverCarTypes = driverCarTypes;
	}

	@OneToMany(mappedBy = "driverMaster")
	public Set<DriverCarTypes> getDriverCarTypes() {
		return driverCarTypes;
	}

	public void setDriverDocumentsLists(Set<DriverDocumentsList> driverDocumentsLists) {
		this.driverDocumentsLists = driverDocumentsLists;
	}

	@OneToMany(mappedBy = "driverMaster")
	public Set<DriverDocumentsList> getDriverDocumentsLists() {
		return driverDocumentsLists;
	}

}
